async function main() {
    console.log('hi')
    

  
}

main().catch(err => console.log(err))